typography_spectrum: 0.1557944422703015
color:
  brandStrength: 0.8381541403957485
  lightness: 0.05443379271609506
  saturation: 0.8477188036284676
  rhythmicContrast: 0.17621509407232008
  brandColors:
    - '#FFFFFF'
    - '#030B51'
    - '#2C3638'
    - '#FF0000'
    - '#7A8181'
github: true
layout_spectrum: 0.5774167312791405
author:
  email: tampahomes@outlook.com
  name: '4511 N Himes Ave, Suite 200, Tampa, Fl 33614'
logo: null
name: BluBay International Realty
navigation:
  - name: Buyers
    url: 'http://www.tampabayareahomelistings.com/info/category/buyers'
    type: external
  - name: Sellers
    url: 'http://www.tampabayareahomelistings.com/info/category/sellers'
    type: external
  - name: Our Team
    url: 'https://www.tampabayareahomelistings.com/about'
    type: external
  - name: Search Homes
    url: 'http://www.tampabayareahomelistings.com/search'
    type: external
  - name: Facebook Page
    url: 'https://www.facebook.com/BluBayRealty/'
    type: external
favicon: null
title: BluBay International Realty
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/7c5531e6-1df1-4182-959d-52287b99891b.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/7c5531e6-1df1-4182-959d-52287b99891b.png
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/40f18a8c-4bfe-4a27-9d04-70779debe91c.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/40f18a8c-4bfe-4a27-9d04-70779debe91c.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/e5da96c1-615b-4d12-88ff-e92ddc156ff5.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/e5da96c1-615b-4d12-88ff-e92ddc156ff5.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/636f4aba-2dd1-48ad-8548-c7f39e63ede2.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/636f4aba-2dd1-48ad-8548-c7f39e63ede2.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/d6b82046-c4f6-404b-954a-0235e91ae69a.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/d6b82046-c4f6-404b-954a-0235e91ae69a.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/e59c77e2-3137-4094-b110-9c9dd8dcf20c.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/e59c77e2-3137-4094-b110-9c9dd8dcf20c.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/3d32cc2a-f565-4d45-8652-cc84feed9c8f.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/3d32cc2a-f565-4d45-8652-cc84feed9c8f.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: 'Tampa Bay Homes - 4511 N. Himes Ave, Suite 200 Tampa, FL 33614'
purpose: []
