layout_spectrum: 0.10481430858392085
typography_spectrum: 0.8781304166060273
color:
  brandStrength: 0.8830135899888223
  lightness: 0.988051421285819
  saturation: 0.0195459623170076
  rhythmicContrast: 0.4826870482269269
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
github: true
author:
  email: tampahomes@outlook.com
  name: '2202 N Westshore Blvd, Suite 200, Tampa, Fl 33607'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ccb1d7a6-52eb-433b-a7e0-f2b0699353d2.png
name: BluBay International Realty
navigation:
  - name: Buyers
    url: 'http://www.tampabayareahomelistings.com/info/category/buyers'
    type: external
  - name: Sellers
    url: 'http://www.tampabayareahomelistings.com/info/category/sellers'
    type: external
  - name: Our Team
    url: 'https://www.tampabayareahomelistings.com/about'
    type: external
  - name: Search Homes
    url: 'http://www.tampabayareahomelistings.com/search'
    type: external
  - name: Facebook Page
    url: 'https://www.facebook.com/BluBayRealty/'
    type: external
favicon: null
title: BluBay International Realty
content: []
description: 'Tampa Bay Homes - 2202 N Westshore Blvd, Suite 200 Tampa, FL 33607'
purpose: []
