typography_spectrum: 0.7304154170798783
color:
  brandStrength: 0.482011868980538
  lightness: 0.5789113692946658
  saturation: 0.8717284826389375
  rhythmicContrast: 0.8466990608598409
  brandColors:
    - '#FCFEFF'
    - '#333B57'
    - '#C7C7D1'
    - '#EC1F25'
    - '#EF6556'
github: true
layout_spectrum: 0.8254319071154672
author:
  email: tampahomes@outlook.com
  name: '2202 N Westshore Blvd, Suite 200, Tampa, Fl 33607'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ccb1d7a6-52eb-433b-a7e0-f2b0699353d2.png
name: BluBay International Realty
navigation:
  - name: Sellers
    url: 'http://www.tampabayareahomelistings.com/info/category/sellers'
    type: external
  - name: Our Team
    url: 'https://www.tampabayareahomelistings.com/about'
    type: external
  - name: Search Homes
    url: 'http://www.tampabayareahomelistings.com/search'
    type: external
  - name: Facebook Page
    url: 'https://www.facebook.com/BluBayRealty/'
    type: external
  - name: Search for your Perfect Home
    url: 'https://www.tampabayareahomelistings.com/search'
    type: external
  - name: Selling? Value your home here
    url: 'https://www.tampabayareahomelistings.com/homevalue/HomeEstimate'
    type: external
favicon: null
title: BluBay International Realty
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/2958b7c1-47d2-4459-8925-50eb02bd50cd.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/2958b7c1-47d2-4459-8925-50eb02bd50cd.png
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: 'Tampa Bay Homes - 2202 N Westshore Blvd, Suite 200 Tampa, FL 33607'
purpose: []
