typography_spectrum: 0.11947883685977005
color:
  brandStrength: 0.2563805391592444
  lightness: 0.03126718912080004
  saturation: 0.41894615581111594
  rhythmicContrast: 0.10564749027823679
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
github: true
layout_spectrum: 0.07377358934417884
author:
  email: tampahomes@outlook.com
  name: '4511 N Himes Ave, Suite 200, Tampa, Fl 33614'
logo: null
name: BluBay International Realty
navigation:
  - name: Buyers
    url: 'http://www.tampabayareahomelistings.com/info/category/buyers'
    type: external
  - name: Sellers
    url: 'http://www.tampabayareahomelistings.com/info/category/sellers'
    type: external
  - name: Search Homes
    url: 'http://www.tampabayareahomelistings.com/search'
    type: external
  - name: Facebook Page
    url: 'https://www.facebook.com/BluBayRealty/'
    type: external
  - name: Get your Home Value
    url: 'http://www.tampabayareahomelistings.com/homevalue/HomeEstimate'
    type: external
favicon: null
title: BlúBay International Realty
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/7c5531e6-1df1-4182-959d-52287b99891b.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/7c5531e6-1df1-4182-959d-52287b99891b.png
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: 'Tampa Bay Homes - 4511 N. Himes Ave, Suite 200 Tampa, FL 33614'
purpose: []
